"""Stable exit codes shared by the CLI and documented in docs/usage.md."""

SUCCESS = 0
VALIDATION_FAILURE = 1
INVALID_USAGE = 2
ENVIRONMENT_FAILURE = 3
UNSAFE_REPOSITORY = 4
TRANSITION_REJECTED = 5
DEPLOYMENT_PREFLIGHT_FAILURE = 6
SECURITY_FAILURE = 7
